<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Xethron\\MigrationsGenerator' => array($vendorDir . '/xethron/migrations-generator/src'),
    'Way\\Generators' => array($vendorDir . '/xethron/laravel-4-generators/src'),
    'Rize\\UriTemplate' => array($vendorDir . '/rize/uri-template/src'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Orangehill\\Iseed' => array($vendorDir . '/orangehill/iseed/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Laracasts\\Flash' => array($vendorDir . '/laracasts/flash/src'),
    'Jlapp\\Swaggervel' => array($vendorDir . '/jlapp/swaggervel/src'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'JakubOnderka\\PhpConsoleColor' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
);
